### ISSUE TITLE
"The 'layerCatalog' setting is incorrect" error message when entering the viewer

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-viewer-app#27]
**Describe the bug**
When entering the viewer application "Visor IDEBarcelona" with ID "15" from "Public" user this error is displayed.

**To Reproduce**
1. Go to 'https://sitmun.github.io/sitmun-viewer-app/auth/login'
2. Click on "Public access"
3. Choose the 'Name: Visor IDEBarcelona / Identifier: 15' application

**Screenshots**
![image](https://github.com/sitmun/sitmun-viewer-app/assets/38311286/7cc62993-9241-4075-9159-73f03cde3017)

**Additional context**
All the elements involved in this application appear to be correct in the admin application.

**Comment by fjlopez** [comment]
@codinachssm @srodriguez7 testing the use of the projects. Update the description/priorities as will.

**Comment by daniboube** [comment]
Removed error message when the layerCatalog option is empty. The remaining error messages are now improved to show more context about the problem itself.

This fix can be tested by accesing application 15 (Visor IDEBarcelona, Alpens, public access on development enviroment). This application has no tasks defined, but the error message is no more.

**Comment by fjlopez** [comment]
@daniboube Why there is no tree? There is a tree in the response https://sitmun-backend-core.herokuapp.com/api/config/client/profile/15/9.  I see an uncaught type error in the javascript console.

<img width="940" alt="image" src="https://github.com/sitmun/sitmun-viewer-app/assets/3294927/7dc738b7-ad91-437d-9819-f269472a82cf">

<img width="580" alt="image" src="https://github.com/sitmun/sitmun-viewer-app/assets/3294927/22068df3-581d-4256-8b74-57cbe81973c4">

**Comment by daniboube** [comment]
@fjlopez As far as I know, there are no tasks in the response, so none of the map elements will be shown, including the layer catalog.

The error you mention must also be related to this, but I'm not sure, since I don't get that error in my environment... I will take a look at it

**Comment by codinachssm** [comment]
It is true that this application has an associated tree, as can be seen in the json response (https://sitmun-backend-core.herokuapp.com/api/config/client/profile/15/9) and in the administration application:
![image](https://github.com/sitmun/sitmun-viewer-app/assets/38311286/04a3889d-454b-472c-87ee-9fd8e2d5f8b4)

Should I open a new issue to report this problem?

**Comment by daniboube** [comment]
I just checked and it is true that there are now defined tasks for this application. After a small fix, the tree should now be visible.

However, we have found an error here regarding the capabilities of a layer. The application (LayerCatalogSilme.js) expects the capabilities to have a single Service attribute, but one of the requests returns a capabilities that contains an array of services. This breaks the implemented logic and causes a blocking error. What should we do in this case?

![imagen](https://github.com/sitmun/sitmun-viewer-app/assets/50242249/959cac76-c410-44ca-b4cd-1c30b23ee5d5)


@IDEmenorca @mvinent

**Comment by codinachssm** [comment]
Is it mandatory to have at least 1 task defined to be able to display the tree? Or was it a coincidence that the first error was solved just when tasks were added to the application?

**Comment by srodriguez7** [comment]
t's not a coincidence. The tools and functionalities associated with the map are configured based on the "tasks" of the configuration json.

In this case, since a "layerCatalog" task had not been configured, the associated functionality was not being loaded, and, therefore, there was no place to display the layers tree.

This is extendable to all the functionalities offered by sitna (and those implemented outside of it), if the task is not in the tasks list of the configuration json, the functionality will not be loaded in the corresponding viewer.

**Comment by codinachssm** [comment]
OK, thanks!!

**Comment by mvinent** [comment]
> I just checked and it is true that there are now defined tasks for this application. After a small fix, the tree should now be visible.
> 
> However, we have found an error here regarding the capabilities of a layer. The application (LayerCatalogSilme.js) expects the capabilities to have a single Service attribute, but one of the requests returns a capabilities that contains an array of services. This breaks the implemented logic and causes a blocking error. What should we do in this case?
> 
> ![imagen](https://private-user-images.githubusercontent.com/50242249/319506191-959cac76-c410-44ca-b4cd-1c30b23ee5d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMDYyMjksIm5iZiI6MTcxMjMwNTkyOSwicGF0aCI6Ii81MDI0MjI0OS8zMTk1MDYxOTEtOTU5Y2FjNzYtYzQxMC00NGNhLWI0Y2QtMWMzMGIyM2VlNWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA4MzIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NjEzNGM0OTYyMmUxNzA2YThlYThlNzA4MjIzMzFiMTE5YWYxZjBkMWU3MDc4ZTgxOThhMTMyZDY1YmU2NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zYGBP47xG_GamFVaEzS7j7RJRIZInN9L3LHDWupNIrM)
> 
> @IDEmenorca @mvinent


It looks like the capabilities from at least one layer ([Divisions Administratives](https://geoserveis.icgc.cat/servei/catalunya/divisions-administratives/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities)) is incorrect, it has the attribute 'Service' twice and that's incorrect according to its own XML schema. We can make a quick fix to prevent the LayerCatalog control from crashing, but I wouldn't do more.

**Comment by fjlopez** [comment]
> Perhaps this should be checked in the "Service-Edit" panel of the admin application, when the admin user creates a new service?

I identify as the root of the problem the handling of the WMS `capabilities` object, which is provided by the SITNA/Openlayers library, rather than an issue with the SITMUN configuration itself.

To address this, I propose a lenient approach towards processing the `capabilities` object. This involves a more flexible interpretation of the WMS 3.0 specification, which requires a `Service` tag by a `Capabilities` tag structure. In a lenient processing context, the `LayerCatalogSilme.js` would not rigidly follow this structure. Instead, it would assume that a well-formed Capabilities object includes at least one `Service` and one `Capabilities` tag, selecting the first instance of both. This strategy accommodates the variability in the Capabilites document observed in this case. 

I reviewed the [existing code](https://github.com/sitmun/sitmun-viewer-app/blob/e8d217f377faa07931dd065fa7bc9750845175e3/src/assets/js/patch/controls/LayerCatalogSilme.js#L568-L602) in the `LayerCatalogSilme.js` file. 

```js
result.parentAbstract = [];
if (capabilities.Service.Abstract) {
  result.parentAbstract = capabilities.Service.Abstract;
}
```

I wonder if an approach similar to the following pseudocode:

```js
if (Array.isArray(capabilities.Service)) {
  currentNode = capabilities.Service[0]
} else {
  currentNode = capabilities.Service
}
result.parentAbstract = [];
if (currentNode.Abstract) {
  result.parentAbstract = currentNode.Abstract;
}
```
could not only mitigate #27 but also to improve the Map Viewer's overall robustness and flexibility in handling OGC capabilities.

**Comment by codinachssm** [comment]
It seems consistent and sufficiently flexible.
@IDEmenorca @mvinent What do you think?

**Comment by mvinent** [comment]
It seems a good way to solve it, if we all agree we can write it and upload it soon.

**Comment by mvinent** [comment]
Solved in [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/df90fc1b615c591e284ddb7070bbee68c19bda63)
