### ISSUE TITLE
Streetview tool: can't see how to close it

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-viewer-app#59]
**Describe the bug**
When using the streetview tool, you cannot see how to close it.

**To Reproduce**
@codinachssm Complete!

**Expected behavior**
@codinachssm Complete!

**Screenshots**
![image](https://github.com/user-attachments/assets/6668a8cc-0562-492a-8469-7814b2cf6c41)

**Desktop (please complete the following information):**
@codinachssm Complete!

**Additional context**
- Screen resolution tested: 1920x1080

**Comment by mvinent** [comment]
We have detected this same bug in our Visor IDE Menorca and solved it today, I'm gonna implement the solution here soon.

**Comment by ibarzrm** [comment]
**Additional information:**
This behavior is only reproduced when the screen is small. In that case, the guide map is placed occupying the entire right side, instead of in the lower right corner.

**Screenshots in small screen**
![image](https://github.com/user-attachments/assets/53c8ccab-fe74-4efc-9e83-aec1fae7eb95)

**Screenshots in big screen**
![image](https://github.com/user-attachments/assets/6842bcba-856a-481d-8835-dd1edf1c13cb)

**Comment by fjlopez** [comment]
It is a bug of API SITNA. It has been reported by @mvinent to IDENA.

**Comment by mvinent** [comment]
Solved on [this commit](https://github.com/sitmun/sitmun-viewer-app/commit/4b63834ff8534214652e12f0ad89e2d9d5f9f7bb).

**Comment by mvinent** [comment]
Validated, StreetView in small screens now can be closed.

![image](https://github.com/user-attachments/assets/8209c349-0a49-4ccd-b368-2aa00bea849e)
